version: '3.9'


services:
  app:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_app
    entrypoint: sh -c "alembic upgrade head
      && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    ports:
      - 9999:8000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:15.1-alpine
    expose:
      - 5432
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d restaurant"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s
  test:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_tests
    entrypoint: sh -c "alembic -c alembic.ini.testing upgrade head
      && pytest"
    depends_on:
      test_db:
        condition: service_healthy
  test_db:
    image: postgres:15.1-alpine
    command: -p 6000
    expose:
      - 6000
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME_TEST}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d restaurant_test -p 6000"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s
  redis:
    image: redis:latest
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
